### PR TITLE
Add member photo for Andrew Lee

### LINKED ISSUE #277: Add member image for Andrew Lee

### PR DESCRIPTION
**Pull request by ctc-devops**
Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #277

### CODE REVIEW

**Comment by alanchangxyz** [comment]
Hmm this should be merged into the `2022-dev-bootcamp-task` branch (and I estimate there will be some merge conflicts because some people merged in their code already, so we'll probably have to fix those) - you can change that by editing this PR and it'll ask you what branch you want to merge your changes into

Go ahead and change the base branch so we can see what actually got changed and then we can review this PR properly 👍

**Comment by leeaj8-uci** [comment]
Whoops, sorry about that! I believe I've changed the branch that it's merging into to `2022-dev-bootcamp-task` and cleaned up the merge conflicts. Let me know if there's anything else you'd like me to do!

**Comment by alanchangxyz** [comment]
Looks like we got some more merge conflicts chief (this may be because of the order I'm merging these PRs in but you're up next so just fix these and it should be good)

**Review by alanchangxyz — CHANGES_REQUESTED** [review]
Ok wait actually before you settle merge conflicts:

- Your LinkedIn URL should be your own not Allison's
- You should fix your Git settings by setting your Git name and email to match your GitHub account (see attached image)
image

**Comment by leeaj8-uci** [comment]
Whoops sorry! I guess my brain is a bit fried from midterm season haha. I've fixed the LinkedIn link and remedied the merge conflicts. I also noticed that my username/email configs were off after the initial commit and tried to correct them for the later ones, but please let me know if there's still issues. Sorry again!

**Review by alanchangxyz — APPROVED** [review]
no need to apologize, this is now a certified LGTM

**Pull request merged**
