### PR TITLE
tn member photo

### LINKED ISSUE #65: Add member image for Thien Nguyen

### PR DESCRIPTION
**Pull request by ctc-devops**
closes #65

### CODE REVIEW

**Comment by thientn4** [comment]
@ZubairSidhu

**Review by ZubairSidhu — CHANGES_REQUESTED** [review]
Looks like there aren't any changes made in this PR. Make sure to follow the steps outlined in the developer onboarding tutorial, and if you are still having trouble, send me a DM on slack or attend the office hours on Oct 31st.

**Review by thientn4 — COMMENTED** [review]
add photo for Thien Nguyen

**Review by ZubairSidhu — COMMENTED** [review]
You have added the photo, but not the code to make this photo appear on the website. Please follow the instructions on the developer onboarding tutorial.

**Comment by thientn4** [comment]
Hi! I have added the code. Sorry since I am quite new to HTML

**Review by ZubairSidhu — CHANGES_REQUESTED** [review]
Looks good, but the photo is too large. Please resize it to the 260x260px.

**Review by ZubairSidhu — APPROVED** [review]

**Pull request merged**
