### PR TITLE
rn member photo

### LINKED ISSUE #118: Add member image for Rochelle Nixon

### PR DESCRIPTION
**Pull request by ctc-devops**
closes #118

### CODE REVIEW

**Review by Vakhshoori101 — COMMENTED** [review]
Everything looks good but can you reupload the image as 260x260 pls :)

**Comment by rochellenixon** [comment]
Sorry about that! Could you check now please?

**Comment by Vakhshoori101** [comment]
thanks for updating your image. Last step is fixing the merge conflict! DM on slack If you need help doing that :)

**Comment by rochellenixon** [comment]
SORRY again! I think it's good now?

**Review by Vakhshoori101 — APPROVED** [review]
LGTM

**Pull request merged**
