### PR TITLE
arjun sivakumar member photo

### LINKED ISSUE #286: Add member image for Arjun Sivakumar

### PR DESCRIPTION
**Pull request by ctc-devops**
Closes #286

### CODE REVIEW

**Review by claudeisakeeb — CHANGES_REQUESTED** [review]
I think you accidentally deleted your changes when you resolved merge conflicts lol

**Comment by ArjunSivakumar13** [comment]
i'm pretty sure my stuff's still there, i just removed duplicate code

**Comment by claudeisakeeb** [comment]
> i'm pretty sure my stuff's still there, i just removed duplicate code

In [this commit ](https://github.com/ctc-uci/commit-the-change-website/pull/295/commits/83eb7f19dcea0d24ff6f4140d953d461887ee1e2) you deleted the changes for your picture. Also in the [files changed ](https://github.com/ctc-uci/commit-the-change-website/pull/295/files) page for this PR it says 0 files are changed

**Comment by ArjunSivakumar13** [comment]
I'm looking at the commit, my changes for my picture are hidden by the expand button. You can see my name if you click expand up.

**Comment by claudeisakeeb** [comment]
> I'm looking at the commit, my changes for my picture are hidden by the expand button. You can see my name if you click expand up.

Ok I see it, not sure how your changes got into the 2022-dev-bootcamp-task lol but lgtm

**Pull request merged**
