### PR TITLE
ck member photo

### LINKED ISSUE #135: Add member image for Celine Kim

### PR DESCRIPTION
**Pull request by ctc-devops**
closes #135

### CODE REVIEW

**Comment by Vakhshoori101** [comment]
You also need to add the image you want to show on the website. Look at other people's PR for help or DM me on slack :)

**Comment by scelinekim** [comment]
Thank you, I just uploaded the photo!

**Comment by Vakhshoori101** [comment]
Thanks for adding the image, but can you please either resize or crop the image to 260x260 :)

**Comment by scelinekim** [comment]
I'm so sorry I reuploaded my image.... sorry and thank you so much

**Review by Vakhshoori101 — APPROVED** [review]
LGTM

**Pull request merged**
