### PR TITLE
Add member image for Rochelle Nixon

### PR DESCRIPTION
**Pull request by rochellenixon**
Closes issue #316

### CODE REVIEW

**Comment by alanchangxyz** [comment]
looks like you've got a merge conflicts to fix with `2022-dev-bootcamp-task` here
worry-frog-hmm

**Comment by alanchangxyz** [comment]
looks like you've got a merge conflicts to fix with 2022-dev-bootcamp-task here 🤔

**Comment by rochellenixon** [comment]
sorry, I don't know why they didn't show up when I pushed yesterday. can you review now?

**Review by alanchangxyz — APPROVED** [review]
yeah this is pretty epic

**Pull request merged**
