### PR TITLE
tl member photo

### LINKED ISSUE #116: Add member image for Tony Liu

### PR DESCRIPTION
**Pull request by ctc-devops**
closes #116

### CODE REVIEW

**Review by Vakhshoori101 — COMMENTED** [review]
everything looks good. Only change is that the image should be 260x260 so please upload a new image of those dimensions :)

**Comment by tonyliu02** [comment]
> everything looks good. Only change is that the image should be 260x260 so please upload a new image of those dimensions :)

Hey Rostam, thank you for pointing that out! I have updated my photo to be 260x260px

**Comment by Vakhshoori101** [comment]
Thanks for resizing the image. Last step is fixing the merge conflict. DM on slack if you need help doing this :)

**Comment by tonyliu02** [comment]
> Thanks for resizing the image. Last step is fixing the merge conflict. DM on slack if you need help doing this :)

Thank you for letting me know! I have resolved the conflict. Please let me know if there is anything else I could do

**Review by Vakhshoori101 — APPROVED** [review]
LGTM

**Pull request merged**
